### PR TITLE
Getting multiple device values at once and function for downloading xml file with device IDs

### PR DESCRIPTION
**Pull request by MervinDelfin**

### CODE REVIEW

**Comment by leoyn** [comment]
Thank you for your pull request.
Before merging I'd like to know why you want to get multiple device values at once. Normally the Gira Homeserver only sends just one device value per action, or am I wrong?
I might change the function name to getDeviceList, just return the file contents to be flexiable how one manages their data and use the sessionToken returned by the Gira Homeserver upon login by default.

**Comment by MervinDelfin** [comment]
It's good idea to change the getDeviceList function.

When setting a listener for all device value changes I noticed that sometimes the server returns multiple values for multiple devices at once. Your code only handled the first value so there was possibility that the program would miss something.

**Comment by MervinDelfin** [comment]
@leoyn can I ask how did you come up with the api? Did you analyze the web traffic of the Gira Homeserver app ?

**Comment by leoyn** [comment]
Yeah kind of. You could also decompile the code from the apk which reveals how you hash the password and where you find the project file.

**Pull request merged**
